#!/bin/sh

echo "Starting test runner..."


test_runner="C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"

tests_dll="C:\Users\98912\Desktop\Sem2\SFT221\ms4\summer24-sft221-zaa-1\root\SourceCode"

failure_string="Failed:"

testout=`"$test_runner" "$tests_dll"`

if [[ $testout == *"$failure_string"* ]]; then
	echo >&2 "Unit test are not passing! Push aborted!"
	exit 1
fi

echo >&2 "All tests run successfully."
exit 0