#!/bin/sh

echo "Starting test runner..."

# Update this path to the location of vstest.console.exe on your machine
test_runner="C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"

# Update this path to the location of your test DLL
tests_dll="C:\Users\yashl\OneDrive\Documents\Yashleen\SFT221\MS4\Main.c"

failure_string="Failed:"

# Run the tests
testout=`"$test_runner" "$tests_dll"`

# Check if any tests failed
if echo "$testout" | grep -q "$failure_string"; then
    echo >&2 "Unit tests are not passing! Push aborted!"
    exit 1
fi

echo >&2 "All tests run successfully."
exit 0
